//
//  ToDoListInteractor.swift
//  CleanToDoList
//
//  Created by Panpan Han  on 2019/3/5.
//  Copyright (c) 2019 Panpan Han . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDoListBusinessLogic
{
  func fetchToDos()
}

protocol ToDoListDataStore
{
  //var name: String { get set }
}

class ToDoListInteractor: ToDoListBusinessLogic, ToDoListDataStore
{
  var presenter: ToDoListPresentationLogic?
  var worker: ToDoListWorker?
  
  func fetchToDos()
  {
    worker = ToDoListWorker()
    worker?.fetchToDos(successHandler: { (todos) in
      presenter?.presentFetchResults(todos: todos)
    })
  }
}
