//
//  ToDoListRouter.swift
//  CleanToDoList
//
//  Created by Panpan Han  on 2019/3/5.
//  Copyright (c) 2019 Panpan Han . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDoListRoutingLogic
{
  func navigateToCreatePage()
}

protocol ToDoListDataPassing
{
  var dataStore: ToDoListDataStore? { get }
}

class ToDoListRouter: ToDoListRoutingLogic, ToDoListDataPassing
{
  weak var viewController: ToDoListViewController?
  var dataStore: ToDoListDataStore?
  
  // MARK: Routing
  
  func navigateToCreatePage() {
    let vc = UIStoryboard(name: "CreateToDo", bundle: nil).instantiateViewController(withIdentifier: "CreateToDo") as! CreateToDoViewController
    viewController?.show(vc, sender: nil)
  }
}
