//
//  ToDoListPresenter.swift
//  CleanToDoList
//
//  Created by Panpan Han  on 2019/3/5.
//  Copyright (c) 2019 Panpan Han . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDoListPresentationLogic
{
  func presentFetchResults(todos: ToDoListModel.ToDoList)
}

class ToDoListPresenter: ToDoListPresentationLogic
{
  weak var viewController: ToDoListDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchResults(todos: ToDoListModel.ToDoList)
  {
    viewController?.fetchItemsSuccess(todos: todos)
  }
}
