//
//  ToDoListWorker.swift
//  CleanToDoList
//
//  Created by Panpan Han  on 2019/3/5.
//  Copyright (c) 2019 Panpan Han . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ToDoListWorker
{
  func fetchToDos(successHandler: (ToDoListModel.ToDoList) -> Void)
  {
    var todos: [ToDoListModel.ToDo] = []
    for index in 1...5 {
      let todo = ToDoListModel.ToDo.init(id: index, content: "Content" + String(index))
      todos.append(todo)
    }
    let viewModel = ToDoListModel.ToDoList.init(todos: todos)
    successHandler(viewModel)
  }
}
